### ISSUE TITLE
Add extensions to `php-core-extensions` config without need of extend

### ISSUE THREAD

**Issue by carusogabriel** [maglnet/ComposerRequireChecker#144]
Hello there. Is it possible to add extensions to the `php-core-extensions` config key without the need of copy and paste the default ones? For example:

This:
```json
{
    "php-core-extensions" : [
        "pcntl",
        "rdkafka"
    ]
}
```

instead of this:
```json
{
    "php-core-extensions" : [
        "Core",
        "date",
        "pcre",
        "Phar",
        "Reflection",
        "SPL",
        "standard",
        "pcntl",
        "rdkafka"
    ]
}
```
?

If I do the first option, I'm getting this error in the CLI:

```bash
ComposerRequireChecker v9.1.2-34-g23c86ac-dev
The following unknown symbols were found:
+--------------------------+--------------------+
| unknown symbol           | guessed dependency |
+--------------------------+--------------------+
| array_walk               | ext-standard       |
| assert                   | ext-standard       |
| is_callable              | ext-standard       |
| is_array                 | ext-standard       |
| gettype                  | ext-standard       |
| count                    | ext-standard       |
| RuntimeException         | ext-SPL            |
| Throwable                | ext-Core           |
| in_array                 | ext-standard       |
| DateInterval             | ext-date           |
| array_merge              | ext-standard       |
| InvalidArgumentException | ext-SPL            |
+--------------------------+--------------------+
```

**Comment by Ocramius** [comment]
@carusogabriel what about handling the `"require"` section instead?

I don't think we should make the config merge the defaults.

**Comment by carusogabriel** [comment]
> @carusogabriel what about handling the "require" section instead?

@Ocramius We've faced a big problem by requiring the `pcntl` and `kafka` extensions in our project, so we've decided to exclude them for now.

> I don't think we should make the config merge the defaults.

Okidoki, thanks for the position.

**Comment by Ocramius** [comment]
> We've faced a big problem by requiring the `pcntl` and `kafka` extensions in our project, so we've decided to exclude them for now.

Note that the package is supposed to expose the pain, not alleviate it :-P
