### ISSUE TITLE
Can't run composer-require-checker on project

### ISSUE THREAD

**Issue by mirandaguillaume** [maglnet/ComposerRequireChecker#156]
Hi ! I'm trying to run composer-require-checker on a project and I get that error
`PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in phar:///usr/local/bin/composer-require-checker/src/ComposerRequireChecker/NodeVisitor/DefinedSymbolCollector.php:50
Stack trace:
#0 phar:///usr/local/bin/composer-require-checker/src/ComposerRequireChecker/NodeVisitor/DefinedSymbolCollector.php(42): ComposerRequireChecker\NodeVisitor\DefinedSymbolCollector->recordClassDefinition(Object(PhpParser\Node\Expr\MethodCall))
#1 phar:///usr/local/bin/composer-require-checker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): ComposerRequireChecker\NodeVisitor\DefinedSymbolCollector->enterNode(Object(PhpParser\Node\Expr\MethodCall))
#2 phar:///usr/local/bin/composer-require-checker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\MethodCall))
#3 phar:///usr/local/bin/composer-require-checker/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpPars in phar:///usr/local/bin/composer-require-checker/src/ComposerRequireChecker/NodeVisitor/DefinedSymbolCollector.php on line 50`

I'm running composer-require-checker check composer.json --ignore-parse-errors

**Comment by Ocramius** [comment]
That's a nesting limitation caused by xdebug: configure thr nesting level in your `.ini` config.

**Comment by mirandaguillaume** [comment]
Oh thx !

**Comment by mirandaguillaume** [comment]
How much should I set the nesting level to ?

**Comment by Ocramius** [comment]
You can set it to `-1` to allow arbitrary nesting (as long as memory allows
it)

**Comment by mirandaguillaume** [comment]
Okay, that's what I did. It's still running 😄

**Comment by mirandaguillaume** [comment]
Thanks, it worked like a charm !

**Comment by mirandaguillaume** [comment]
I have unknown dependencies on ext-Core for exemple, what should I do ? Add it to composer.json ?
I have a config file with php-core-extensions and Core

**Comment by mirandaguillaume** [comment]
It seems I'm scanning the vendor directory, is that normal ?

**Comment by mirandaguillaume** [comment]
Figured it out by reading old closed issues.
Thx anyway !
