### ISSUE TITLE
LocateASTFromFiles trying to read directories as files on PHP 7.4

### ISSUE THREAD

**Issue by Majkl578** [maglnet/ComposerRequireChecker#172]
Ón PHP 7.4 this new error appears:

```
Notice:  file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory in phar:///usr/local/bin/composer-require-checker/src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php on line 35
Stack trace:
  1. {main}() /usr/local/bin/composer-require-checker:0
  2. include() /usr/local/bin/composer-require-checker:10
  3. ComposerRequireChecker\Cli\Application->run() phar:///usr/local/bin/composer-require-checker/bin/composer-require-checker.php:32
  4. ComposerRequireChecker\Cli\Application->doRun() phar:///usr/local/bin/composer-require-checker/vendor/symfony/console/Application.php:145
  5. ComposerRequireChecker\Cli\Application->doRunCommand() phar:///usr/local/bin/composer-require-checker/vendor/symfony/console/Application.php:262
  6. ComposerRequireChecker\Cli\CheckCommand->run() phar:///usr/local/bin/composer-require-checker/vendor/symfony/console/Application.php:901
  7. ComposerRequireChecker\Cli\CheckCommand->execute() phar:///usr/local/bin/composer-require-checker/vendor/symfony/console/Command/Command.php:255
  8. ComposerRequireChecker\DefinedSymbolsLocator\LocateDefinedSymbolsFromASTRoots->__invoke() phar:///usr/local/bin/composer-require-checker/src/ComposerRequireChecker/Cli/CheckCommand.php:79
  9. ComposerRequireChecker\ASTLocator\LocateASTFromFiles->__invoke() phar:///usr/local/bin/composer-require-checker/src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRoots.php:27
 10. file_get_contents() phar:///usr/local/bin/composer-require-checker/src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php:35
```

**Comment by maglnet** [comment]
This should be fixed with release 2.1.0

@Majkl578 could you please verify?

**Comment by Majkl578** [comment]
Not fixed in 2.1.0 unfortunately, still seeing `PHP Notice:  file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory in phar:///usr/local/bin/composer-require-checker/src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php` errors. :(

**Comment by Photon89** [comment]
I just ran into the same problem. Looks like foreach now also lists "." and ".." as files in a directory, so when looping over them the loop variable $file also gets the values "." and "..".

**Comment by Ocramius** [comment]
@Photon89 do you have a code location to reference, or maybe a test case?

**Comment by Photon89** [comment]
@Ocramius Yep, this loop: https://github.com/maglnet/ComposerRequireChecker/blob/6022d233935615c4454a462c0607aa5b834fd93c/src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php#L34

**Comment by Majkl578** [comment]
For reference, I am still seeing the same issue as well on our CI.

**Comment by Photon89** [comment]
A quick and dirty fix which I used in my app, just exclude "." and ".." by hand while looping: https://gitlab.com/Photon89/tpiq-experimental/-/commit/d6af93f5bf02c1b1fadbbffc842a92ce424c506d

**Comment by Ocramius** [comment]
Would probably check which iterator is passed in instead, instead of fixing the symptom

**Comment by Photon89** [comment]
I'm a rookie in programming, would be grateful to some documentation reference for a better fix. :)
