### ISSUE TITLE
query re: compatibility with symfony/console:^5

### ISSUE THREAD

**Issue by SignpostMarv** [maglnet/ComposerRequireChecker#173]
I've a general preference for using `composer require --dev` rather than using global installs/phar builds.

Are there any plans to nudge up compatibility with symfony/console, i.e. `symfony/console:^4.4|^5.0` ?

**Comment by Ocramius** [comment]
> Are there any plans to nudge up compatibility with symfony/console, i.e. `symfony/console:^4.4|^5.0` ?

@dependabot is running on this repo, and keeping things up-to-date once a month or so.

A release for 2.1.0 is probably required anyway (see #172 and #171).

Closing here meanwhile.
