### ISSUE TITLE
Cannot identify XSLTProcessor

### ISSUE THREAD

**Issue by unional** [maglnet/ComposerRequireChecker#180]
https://www.php.net/manual/en/class.xsltprocessor.php

I have code that uses this class. 

I tried to add `libxml` and then `libxslt`, `xsl`, `xslt`, or`Xsl` to `php-core-extensions` section of the config but it does not work.

What should I do in the config to add that extension? 🌷

**Comment by Ocramius** [comment]
I wonder if this is a bug in php-src? You should try by adding `ext-xsl` to your `"require"` section first.

**Comment by unional** [comment]
Got it. Thanks. My case is a bit special. The code is actually not executing on my dev machine but on a separate device, which have a different php built. And I'm not really using `composer` to package and deploy the code. Thus I miss the `ext-xsl` in the `composer.json`. 

Thanks for your help!

🌷
