### ISSUE TITLE
symfony-pack dependencies

### ISSUE THREAD

**Issue by freezy-sk** [maglnet/ComposerRequireChecker#184]
Hi
Currently installed `symfony-pack` packages (symfony flex metapackages) are shown as soft dependencies (that's right). But wouldn't it be better to resolve them as hard dependency?
Or every `symfony-pack` packages should be unpacked to properly show them as real dependency?
These symfony-pack packages like `orm` or `twig-pack` are really convenient for users because they require everything what is needed for whole functionality and installing this packs are advised in Symfony documentation.
What is your opinion about installing these packs or how to handle this kind of dependencies?
Unpacking every `symfony-pack` is not really convenient.

**Comment by Ocramius** [comment]
packs are not really dependencies, but rather "installation utilities", and can change at any time: you should really specify dependencies that your sources depend upon.

I also endorse not using packs, contrary to symfony documentation 😛

**Comment by freezy-sk** [comment]
@Ocramius I'm unpacking all packs in my projects, but as you pointed, sometimes they change. Do you have some advice how to handle these situations? In bigger teams it's hard to require from project owners to unpack or to unpack and check changes of that packs all the time.

**Comment by Ocramius** [comment]
well, packs are really only needed at first installation. If this tool is part of the CI pipeline, you already have something forcing unpacking 🤔

**Comment by freezy-sk** [comment]
Thanks, good point about that first installation. This tool is not part of our current CI pipeline, but I'm preparing steps to require it in every project CI. And you know how developers likes changes 😄

**Comment by SvenRtbg** [comment]
I'd add that even Fabien recommends unpacking the packs: http://fabien.potencier.org/symfony4-unpack-the-packs.html

And after that you have the correct dependencies for the scan.
