### ISSUE TITLE
Adding support of SF 4.4

### ISSUE THREAD

**Issue by HVSoftware** [maglnet/ComposerRequireChecker#185]
maglnet/composer-require-checker has a hard dependency on symfony/console:^5.0. For this reason one of our project in which we want to support ^4.4 and ^5.0 doesn't work.

Is it possible to include SF 4.4 support?

`"symfony/console": "^4.4 || ^5.0",`

This way we can still use the package in our current projects and slowly move to SF 5.0.

**Comment by Ocramius** [comment]
The library dos not necessarily need to be installed in `vendor` as `require-dev`: you can run

```sh
mkdir /tmp/my-installation-path
cd /tmp/my-installation-path
composer require maglnet/composer-require-checker:9.9.9 # use exact version here, to be sure
cd - /tmp/my-installation-path/vendor/bin/composer-require-checker

```

**Comment by Ocramius** [comment]
Also: can use the phar installation if not needed :+1:

**Comment by HVSoftware** [comment]
We used the solution and this is working. Thank you
