### ISSUE TITLE
False positive in case of replaced package

### ISSUE THREAD

**Issue by Jean85** [maglnet/ComposerRequireChecker#188]
I'm getting a false positive with a replaced package. The reproducer is:
`composer.json`
```
{
    "name": "foo/bar",
    "require": {
        "jean85/pretty-package-versions": "1.3.0",
        "ocramius/package-versions": "^1.3"
    }
}
```
PHP Code:
```php
<?php
echo \PackageVersions\Versions::ROOT_PACKAGE_NAME;
```
Code should output `foo/bar`; `PackageVersions\Versions` is from `ocramius/package-versions`, but `jean85/pretty-package-versions` 1.3.0 [uses a replaciing fork](https://packagist.org/packages/jean85/pretty-package-versions#1.3.0), [`composer/package-versions-deprecated` ^1.8.0](https://github.com/composer/package-versions-deprecated).

That fork is just a patched version which backports support to PHP 7.0, declared classes are the same, so the check shouldn't fail.

**Comment by Ocramius** [comment]
what's the actual output?

**Comment by Jean85** [comment]
The output is still correct, the only defect here is the false positive with this package (the ComposerRequireChecker).

**Comment by Ocramius** [comment]
@Jean85 I mean that your OP does not include "expected" vs "actual".

**Comment by Jean85** [comment]
@Ocramius wops, you pointed me to the real issue! Sorry for misunderstanding.

The output is:
```
ComposerRequireChecker 0.17.1-164-g7abd6a5-dev
The following unknown symbols were found:
+--------------------------+--------------------+
| unknown symbol           | guessed dependency |
+--------------------------+--------------------+
| PackageVersions\Versions |                    |
+--------------------------+--------------------+
```

I have `"maglnet/composer-require-checker": "^2.0"` in my `composer.json` so something's up with my CI. I've re-run locally and it works.

Sorry.
