### ISSUE TITLE
Syntax error, unexpected T_MATCH

### ISSUE THREAD

**Issue by rieschl** [maglnet/ComposerRequireChecker#196]
We encounter some strange behavior lately. On some projects/libraries, the checker returns the following error:

```
$ vendor/bin/composer-require-checker
ComposerRequireChecker 2.1.0@0c66698d487fcb5c66cf07108e2180c818fb2e72

In ParserAbstract.php line 315:

  Syntax error, unexpected T_MATCH on line 15


check [--config-file CONFIG-FILE] [--ignore-parse-errors] [--] [<composer-json>]
```

It seems to be somehow related to PHPunit when it is installed as non-dev dependency.
Psalm also had a similar problem but fixed it already: https://github.com/vimeo/psalm/issues/3901

The error disappears when I remove the `extends Match` from `\PHPUnit\Framework\MockObject\Builder\ParametersMatch` lins 15.

Anyone has a clue what's going on there?

**Comment by Ocramius** [comment]
Possibly new PHP-Parser running with PHP 8.x compat? `match` became a keword since `php:8-alpha`

**Comment by rieschl** [comment]
Hmm, sorry I forgot to mention the versions. PHP `7.4.7`, `phpunit/phpunit: 9.2.6`, `maglnet/composer-require-checker: 2.1.0`.

When checking the version, I discovered, that this bug seems to be gone in PHP `7.4.8`.
Let me check that and I'll come back with the results.

**Comment by rieschl** [comment]
ok... it's not related to the PHP version, but version of `nikic/php-parser`. There is no error with version `4.6.*`,  only with the current `4.7.*`.
If I interpret this correctly, that's not a problem with this library but with `php-parser` being too strict and/or phpunit which uses a keyword which will be reserved in PHP8, right?
`psalm` "resolved" this problem by [restricting php-parser versions](https://github.com/vimeo/psalm/commit/3f06d4f706e556f5535ba2acba4168ca775299df).

**Comment by Ocramius** [comment]
I don't think the version should be restricted there: rather, the parser being used should be configured.

I think it's configured correctly here: https://github.com/maglnet/ComposerRequireChecker/blob/c0c2e27011ce0e227d0b702ac1aa1b3d3c2d5972/src/ComposerRequireChecker/Cli/CheckCommand.php#L158

Probably need to report an issue upstream.

**Comment by rieschl** [comment]
> 
> 
> Probably need to report an issue upstream.

There is, already: https://github.com/nikic/PHP-Parser/issues/690

**Comment by andrewmy** [comment]
As commented by @nikic in that issue,
> It should now be possible to control the emulation level by passing ['phpVersion' => '7.4'] to the emulative lexer.

So still needs a fix here.

**Comment by nikic** [comment]
You might also just want to not use emulation at all for this use case (i.e. parse for the PHP version you're running on).

**Comment by andrewmy** [comment]
@nikic do you mean passing `new Lexer()` to the `ParserFactory`?

**Comment by rieschl** [comment]
Follow-up: It works for me now with `2.1.0`. It seems that php-parser uses the running PHP version to parse the code.

**Comment by Baptouuuu** [comment]
Hi,

I still have the problem with `nikic/php-parser` `4.9.1` and `maglnet/composer-require-checker` `2.1.0`. @rieschl did you change anything else to make it work ?

**Comment by rieschl** [comment]
no, I did not change anything. which php version do you use?

**Comment by Baptouuuu** [comment]
7.4

**Comment by rieschl** [comment]
You're right. My error didn't disappear because of a new php-parser version but because PHPUnit removed the offending class: https://github.com/sebastianbergmann/phpunit/commit/b57cd45d8d8626d5b9b38547b85094a8a7160712
`match` is a reserved keyword in PHP8 (it's a function/control structure there [[src]](https://wiki.php.net/rfc/match_expression_v2)) so they have to get rid of it anyway. If I checked correctly that change was in `9.3.0`, so you can try to update to the latest PHPUnit and see if the error goes away.
Of course, if you use PHP8 stuff somewhere else that won't help much.
