### ISSUE TITLE
Required parameter follows optional parameter

### ISSUE THREAD

**Issue by iggyvolz** [maglnet/ComposerRequireChecker#202]
Running composer-require-checker in PHP 8 (related: #201) throws the following deprecation warning:
```
Deprecated: Required parameter $rootDir follows optional parameter $globPatterns in /composer/vendor/maglnet/composer-require-checker/src/ComposerRequireChecker/FileLocator/LocateFilesByGlobPattern.php on line 17
```

https://github.com/maglnet/ComposerRequireChecker/blob/196131edee2bcc948fdbe6be578120a411016bfa/src/ComposerRequireChecker/FileLocator/LocateFilesByGlobPattern.php#L17

Likely don't want to specify [] as the default for `$globPatterns` as that cannot be used directly.

**Comment by Ocramius** [comment]
Fairly sure that the default value can be dropped - can you try sending a patch?

**Comment by Ocramius** [comment]
Thanks @iggyvolz!
