### ISSUE TITLE
Unknown symbol Composer\InstalledVersions

### ISSUE THREAD

**Issue by a-menshchikov** [maglnet/ComposerRequireChecker#217]
When using `Composer\InstalledVersions` in my code, composer-require-checker show me the message about unknown symbol with this class.
I tried add `"composer-runtime-api": "^2.0"` in composer.json, but that didn't help.

**Comment by Ocramius** [comment]
I think it needs to be whitelisted, since `composer-runtime-api` does not really follow any `vendor/*` autoloading convention.

Can you send a patch?
