### ISSUE TITLE
json decoding is not handling nicely

### ISSUE THREAD

**Issue by keradus** [maglnet/ComposerRequireChecker#22]
output of json_decode is not handled, thus in case of any json-violation, we got following error:
```
Type error: Argument 1 passed to ComposerRequireChecker\Cli\Options::__construct() must be of the type array, null given, called in ...
```

**Comment by Ocramius** [comment]
Meh, is it really worth checking this? The only difference would be the better exception message

**Comment by keradus** [comment]
without debugging what is a referred class and how param for it was generated, I had no clue that it's due to JSON syntax violation...

**Comment by Ocramius** [comment]
Gotcha, makes sense.

**Comment by keradus** [comment]
thanks :+1:
