### ISSUE TITLE
Option for PHP built-in symbols

### ISSUE THREAD

**Issue by szepeviktor** [maglnet/ComposerRequireChecker#221]
Could you add an option to whilelist [built-in symbols](https://github.com/maglnet/ComposerRequireChecker/blob/master/data/config.dist.json#L3-L5)?
Now users have to keep that list in `symbol-whitelist`.

**Comment by Ocramius** [comment]
That's only if you use your own `config-file` though: seems acceptable as a trade-off?

**Comment by szepeviktor** [comment]
Thank you.

> That's only if you use your own `config-file`

Are there users not using a custom configuration file?? 😲

**Comment by Ocramius** [comment]
@szepeviktor the tool works OOTB if your project is in good shape :-)

**Comment by szepeviktor** [comment]
I should then get a box.

# 🗳️

Thank you!
