### ISSUE TITLE
Add release automation tooling

### ISSUE THREAD

**Issue by Ocramius** [maglnet/ComposerRequireChecker#235]
This is about installing https://github.com/laminas/automatic-releases

In practice, we need following repository secrets to be configured by @maglnet:

 * `GIT_AUTHOR_EMAIL`
 * `GIT_AUTHOR_NAME`
 * `ORGANIZATION_ADMIN_TOKEN` (a personal token should suffice, but it needs admin rights on the repo)
 * `SIGNING_SECRET_KEY` a private passwordless GPG **subkey** to be used for signing releases

**Comment by maglnet** [comment]
@Ocramius 
I just added the mentioned secrets and added the release workflow within #236 but I'm not familiar with this, so maybe you could give some input what needs to be done next or simply merge the MR and finish milestone 3.1.0 to create a release?

**Comment by Ocramius** [comment]
@maglnet let's schedule a call and I'll show you :+1:
