### ISSUE TITLE
File location doesn't work

### ISSUE THREAD

**Issue by SpacePossum** [maglnet/ComposerRequireChecker#25]
Using something like this in `composer.json` doesn't work:

```json
    "autoload": {
        "psr-4": {
            "GeckoPackages\\PHPUnit\\": "src\\PHPUnit"
        }
    },
```

This does:

```json
"autoload": {
        "psr-4": {
            "GeckoPackages\\PHPUnit\\": "src/PHPUnit/"
        }
    },
```

What is also a bit tricky is that the tool ends with;
```
[12:07 PM]-[possum@zoo1]-[/home/possum/work/GeckoPHPUnit]-[git 2.0] 
$ ./vendor/bin/composer-require-checker check composer.json --config-file=/home/possum/work/GeckoPHPUnit/.composer-require-checker.json -vvv
ComposerRequireChecker v2.1-4-g74c9d72-dev
There were no unknown symbols found.
```

Might be better to do a sanity check if there were any symbols found at all and if not exit with an error that the configuration is off?

Meta stuff for debugging:
```
[12:07 PM]-[possum@zoo1]-[/home/possum/work/GeckoPHPUnit]-[git 2.0] 
$ php -v
PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul  7 2017 09:41:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.7-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

```
[12:07 PM]-[possum@zoo1]-[/home/possum/work/GeckoPHPUnit]-[git 2.0] 
$ composer -V
Composer version 1.4.2 2017-05-17 08:17:52
```

There is also a minor thingy about locating the passed configuration file when the tool is installed in `/usr/local/bin/` but run from other `cws` dir.

I'll hope to prep. some fixes for this the upcoming days :)

**Comment by Ocramius** [comment]
`"src\\PHPUnit"` is not a valid path

**Comment by SpacePossum** [comment]
Interesting as I did the setup here https://github.com/GeckoPackages/GeckoPHPUnit/blob/v2.1/composer.json#L16 and travis passes for Linux (as well as local Linux setup), secondly it is used on PHP-CS-Fixer in the test suit which tests on Windows systems as well.
I'm not disputing your claim of the path being invalid, I'm just curious about this case:)

**Comment by Ocramius** [comment]
Probably needs to be escalated to composer itself, but `\\` is absolutely not a path separator.

**Comment by SpacePossum** [comment]
The `\\` is json escaping of `\`, so the issue not dealing with something like `a\b\test.php` correcty.
Closing as discussion can be done better in the PR.
