### ISSUE TITLE
Release 3.3.0

### ISSUE THREAD

**Issue by massimilianobraglia** [maglnet/ComposerRequireChecker#267]
Hello there,

thank you for this great library! Just a quick question: any plans on releasing 3.3.0?

I saw that this update https://github.com/maglnet/ComposerRequireChecker/pull/241 has been merged but still not released. I'm sorry for bothering with this one, but that update permits the usage of glob library on systems without `GLOB_BRACE` constant.

Obviously, this is not a complaint. Just a question :)

Thank you! 😄

**Comment by Ocramius** [comment]
If you run a `composer require malgnet/composer-require-checker`, you already get the latest dependencies

**Comment by Ocramius** [comment]
Related: https://github.com/maglnet/ComposerRequireChecker/issues/256

**Comment by massimilianobraglia** [comment]
Fair enough, thank you, @Ocramius!
