### ISSUE TITLE
Catch parser error and rethrow with file information

### ISSUE THREAD

**Issue by bobvandevijver** [maglnet/ComposerRequireChecker#272]
Whenever a PHP parse error occurs, only the parse error is shown, without information about the conflicting file.

```
  [PhpParser\Error]
  Syntax error, unexpected T_MATCH on line 26
```

If I'm correct, it should be pretty trivial to catch this exception in the `ASTLocator`, and rethrow it with a own message that does include the actual file path.

https://github.com/maglnet/ComposerRequireChecker/blob/79c852fda6cffe089cb49e435570a8bbd43091b3/src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php#L40

**Comment by Ocramius** [comment]
@bobvandevijver please do send a patch with a test addition ( https://github.com/maglnet/ComposerRequireChecker/blob/79c852fda6cffe089cb49e435570a8bbd43091b3/test/ComposerRequireCheckerTest/ASTLocator/LocateASTFromFilesTest.php )
