### ISSUE TITLE
Recursively find files

### ISSUE THREAD

**Issue by steevanbarboyon** [maglnet/ComposerRequireChecker#279]
Hi,

With `scan-files` I can't recursively find files: `foo/*.php` will only search in `foo` directory, not in subdirectories.

Ho can I do it?

Thanks

**Comment by DanielBadura** [comment]
`scan-files` follow the glob pattern. So as far as i know it should be possible but never tried it myself or have seen it in the tests here. See here the glob pattern syntax: https://github.com/webmozarts/glob

`/foo/**/*.php` should maybe do the trick.

**Comment by steevanb** [comment]
Ok thanks, you can close this issue :)

**Comment by DanielBadura** [comment]
Did it worked out?

**Comment by crocodele** [comment]
I can confirm that `foo/**/*.php` works for me. I guess this issue can be closed by someone with the power to do so. :slightly_smiling_face:
