### ISSUE TITLE
Publish public key on keys.openpgp.org

### ISSUE THREAD

**Issue by eclipxe13** [maglnet/ComposerRequireChecker#286]
Could you please consider to add the public key used to sign the released phar file on https://keys.openpgp.org ?

It could be that the key was published on `sks-keyservers.net` but it is not available anymore since 2021-06-21

It is not possible to install `ComposerRequireChecker` using `phive`. See phar-io/phive#317

Thanks a lot for your great work on this project!

**Comment by Ocramius** [comment]
You can take the key from https://github.com/maglnet.gpg and publish it to your keyring of preference: doesn't require the author of the key.

**Comment by eclipxe13** [comment]
Uhm, I might be wrong, but the key on https://github.com/maglnet.gpg is related with the key used to create https://github.com/maglnet/ComposerRequireChecker/releases/download/3.3.0/composer-require-checker.phar.asc ?

- composer-require-checker.phar.asc is using `343FAC404EB57FFEF19C0255032228317452FB59`
```
gpg: assuming signed data in 'composer-require-checker.phar'
gpg: Signature made Thu Jul  8 11:58:14 2021 UTC
gpg:                using RSA key 343FAC404EB57FFEF19C0255032228317452FB59
gpg:                issuer "magl@magl.net"
```

- maglnet.gpg contains: `B0906BA775992B910F4E83CBD2CCAC42F6295E7D`
```
pub   rsa4096/D2CCAC42F6295E7D 2013-09-04 [SCA] [expires: 2023-01-18]
      B0906BA775992B910F4E83CBD2CCAC42F6295E7D
uid                           Matthias Glaub <matthias@glaub-online.de>
uid                           Matthias Glaub <info@8db8.de>
uid                           Matthias Glaub <magl@magl.net>
uid                           Matthias Glaub <maglnet@keybase.io>
sub   rsa4096/C942D9E20BB74EE9 2013-09-04 [E] [expires: 2023-01-18]
sub   rsa4096/033E5F8D801A2F8D 2021-01-18 [S] [expires: 2023-01-18]
```

**Comment by maglnet** [comment]
Hi,
I'll check this later. Maybe I used the wrong key for signing this phar file.

**Comment by maglnet** [comment]
@eclipxe13  I think I messed up something and hope its fine now. I added a new signature. Could you please verify it's ok now?

**Comment by eclipxe13** [comment]
It works! thank you @maglnet !

```
mkdir -p /tmp/x/gpg
cd /tmp/x/
wget https://github.com/maglnet.gpg
wget https://github.com/maglnet/ComposerRequireChecker/releases/download/3.3.0/composer-require-checker.phar
wget https://github.com/maglnet/ComposerRequireChecker/releases/download/3.3.0/composer-require-checker.phar.asc

gpg --homedir /tmp/x/gpg --import maglnet.gpg
gpg: WARNING: unsafe permissions on homedir '/tmp/x/gpg'
gpg: keybox '/tmp/x/gpg/pubring.kbx' created
gpg: /tmp/x/gpg/trustdb.gpg: trustdb created
gpg: key D2CCAC42F6295E7D: public key "Matthias Glaub <matthias@glaub-online.de>" imported
gpg: Total number processed: 1
gpg:               imported: 1

gpg --homedir /tmp/x/gpg --verify composer-require-checker.phar.asc 
gpg: WARNING: unsafe permissions on homedir '/tmp/x/gpg'
gpg: assuming signed data in 'composer-require-checker.phar'
gpg: Signature made Sun Aug  1 01:09:57 2021 CDT
gpg:                using RSA key B2BDAAAC6F1FDE528CD9EEC9033E5F8D801A2F8D
gpg:                issuer "magl@magl.net"
gpg: Good signature from "Matthias Glaub <matthias@glaub-online.de>" [unknown]
gpg:                 aka "Matthias Glaub <info@8db8.de>" [unknown]
gpg:                 aka "Matthias Glaub <magl@magl.net>" [unknown]
gpg:                 aka "Matthias Glaub <maglnet@keybase.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: B090 6BA7 7599 2B91 0F4E  83CB D2CC AC42 F629 5E7D
     Subkey fingerprint: B2BD AAAC 6F1F DE52 8CD9  EEC9 033E 5F8D 801A 2F8D
```

For the record if anyone get here because cannot install ComposerRequireChecker using `phive` global install:

```
sudo gpg --homedir /usr/local/lib/phive/gpg/ --import /tmp/maglnet.gpg
sudo phive install --global composer-require-checker
```

I see the @Ocramius answer about not publishing the public key on openpgp.org, and also read on the issues about removing phar distribution method. But please, consider to publish the key on https://keys.openpgp.org, at least while phar and signature file is available.

**Comment by theseer** [comment]
> You can take the key from [@maglnet.gpg](https://github.com/maglnet.gpg) and publish it to your keyring of preference: doesn't require the author of the key.

While that may have been the case in the past, modern and more secure gpg key servers like `keys.openpgp.org` require a confirmation for every UID included. When uploaded, the server will send an email with a verification code to each, not listing it until confirmed.

**Comment by theseer** [comment]
Reading it again, the wording might have been confusing:

> You can take the key from @maglnet.gpg and publish it to your keyring of preference.

A Keyring is usually a local thing, nothing you would "publish" something to but rather import ;)
I assume you meant key server rather than keyring in my comment above.

**Comment by maglnet** [comment]
The key has been published to `keys.openpgp.org` now, too.
