### ISSUE TITLE
Parse error with PHP 8.1 code

### ISSUE THREAD

**Issue by DaFox** [maglnet/ComposerRequireChecker#348]
The parser doesn't handle the new "readonly" keyword properly and throws an error:

```
ComposerRequireChecker 4.0.0@baa11a4e9e5072117e3d180ef16c07036cafa4a2
In LocateASTFromFiles.php line 46:
                                                                               
  Parsing the file [ [...] /main/vendor/google/apiclient-services/src/Fire  
  store/ReadOnly.php] resulted in an error: Syntax error, unexpected T_READON  
  LY, expecting T_STRING on line 20                                            
                                                                               
In ParserAbstract.php line 318:
                                                                      
  Syntax error, unexpected T_READONLY, expecting T_STRING on line 20  
                                                                      
check [--config-file CONFIG-FILE] [--ignore-parse-errors] [--output OUTPUT] [--] [<composer-json>]
BUILD FAILED
```

**Comment by Ocramius** [comment]
Are you running with latest dependencies overall?

**Comment by DaFox** [comment]
@Ocramius Sorry, what dependencies are you talking about?

The require-checker used is the PHAR-Archive downloaded from here:
https://github.com/maglnet/ComposerRequireChecker/releases/download/4.0.0/composer-require-checker.phar

The `composer.json` essentially contains the following dependencies:

```
"google/apiclient": "2.12.1",
"google/apiclient-services": "0.238.1",
"guzzlehttp/guzzle": "7.4.2",
"guzzlehttp/psr7": "2.2.1",
```

Runtime is PHP 8.1.3 CLI on Debian 11.0, with some extra extensions. Nothing special. 

TIA

**Comment by Ocramius** [comment]
Can you try a normal composer installation, please?

Fairly sure these are just dependencies that were locked in the PHAR release at that time.

Related: #256

**Comment by underdpt** [comment]
I'm also having this usin a normal composer installation:

```
In LocateASTFromFiles.php line 46:
                                                                                                                                                                    
  Parsing the file [D:/desarrollos/enertrade.es/api.enertrade.es/vendor/yajra/laravel-datatables-html/src\Html\Editor\Fields\ReadOnly.php] resulted in an error:    
  Syntax error, unexpected T_READONLY, expecting T_STRING on line 5                                                                                                 
```

**Comment by Ocramius** [comment]
Can you adjust this and see if it makes a difference? 

https://github.com/maglnet/ComposerRequireChecker/blob/fb2a69aa2b7307541233536f179275e99451b339/src/ComposerRequireChecker/Cli/CheckCommand.php#L266

**Comment by underdpt** [comment]
The line is exactly the same I have on vendor/maglnet/composer-require-checker/src/ComposerRequireChecker/Cli/CheckCommand.php

If you mean changing the constant `PREFER_PHP7`, on my `nikic/php-parser` installation it only allows for this:

```php
    const PREFER_PHP7 = 1;
    const PREFER_PHP5 = 2;
    const ONLY_PHP7 = 3;
    const ONLY_PHP5 = 4;
```

But after further reviewing, I see that the faulty file contains:

```php
<?php

namespace Yajra\DataTables\Html\Editor\Fields;

class ReadOnly extends Field
{
    protected $type = 'readonly';
}
```

And `readonly` is a reserved keyword since php 8.1. I just upgraded the package and the error is gone!

**Comment by Ocramius** [comment]
So it is a problem with dependencies, as I stated above 😜

**Comment by SvenRtbg** [comment]
Problems solved? @DaFox @underdpt ?

**Comment by underdpt** [comment]
Long time since last tried :-)

Just installed it on a project, works perfectly (spotted a few old libraries which still were being referenced and a missing php extension). Great!

**Comment by Ocramius** [comment]
Closing here then 👍
