### ISSUE TITLE
Exception because of invalid php (xml) file in symfony/dependency-injection

### ISSUE THREAD

**Issue by server-may-cry** [maglnet/ComposerRequireChecker#35]
```
# vendor/bin/composer-require-checker -vvv
ComposerRequireChecker b58b51e-dev

                                               
  [PhpParser\Error]                            
  Syntax error, unexpected T_STRING on line 1  
                                               

Exception trace:
 () at /app/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:293
 PhpParser\ParserAbstract->parse() at /app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php:50
 PhpParser\Parser\Multiple->tryParse() at /app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php:31
 PhpParser\Parser\Multiple->parse() at /app/vendor/maglnet/composer-require-checker/src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php:28
 ComposerRequireChecker\ASTLocator\LocateASTFromFiles->__invoke() at /app/vendor/maglnet/composer-require-checker/src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRoots.php:28
 ComposerRequireChecker\DefinedSymbolsLocator\LocateDefinedSymbolsFromASTRoots->__invoke() at /app/vendor/maglnet/composer-require-checker/src/ComposerRequireChecker/Cli/CheckCommand.php:72
 ComposerRequireChecker\Cli\CheckCommand->execute() at /app/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:888
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:224
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at /app/vendor/maglnet/composer-require-checker/bin/composer-require-checker.php:32
 include() at /app/vendor/maglnet/composer-require-checker/bin/composer-require-checker:3

check [--config-file CONFIG-FILE] [--] [<composer-json>]
```
That happened when try to parse invalid php file in [symfony/dependency-injection](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Tests/Fixtures/xml/xml_with_wrong_ext.php)
Only if symfony/dependency-injection specified in my composer.json file

**Comment by Ocramius** [comment]
What's the file?

**Comment by server-may-cry** [comment]
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Tests/Fixtures/xml/xml_with_wrong_ext.php

**Comment by Ocramius** [comment]
@maglnet should we just ignore any PHP we can't parse?

Also, why is `Tests` being included? Should we exclude that too?

**Comment by maglnet** [comment]
@Ocramius if we cannot parse PHP we could raise this as a warning or make it configureable as a parameter / config file flag.  
I would also suggest to add exclude glob patterns to the default config, so it would be possible to exclude only the problematic files/paths.  

@server-may-cry 
do you have short-tags enabled within your php installation?
`php -i | grep short_open_tag`

**Comment by server-may-cry** [comment]
@maglnet 
```
# php -i | grep short_open_tag
short_open_tag => On => On
```

I think we must take care about [exclude-from-classmap`](https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps) option https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/composer.json#L45

**Comment by Ocramius** [comment]
That's possible via BetterReflection, I suppose, but still very expensive.
In pseudo-code:

 1. Find all class names
 2. Get the AST for each

Note that this doesn't include scripts though, so the approach may be wrong.
