### ISSUE TITLE
mixed parameter type

### ISSUE THREAD

**Issue by willemstuursma** [maglnet/ComposerRequireChecker#354]
We got the following output: 

```
ComposerRequireChecker 4.1.0@4d18781ae098802cb784f42454ef2477d6a95a4f
The following 1 unknown symbols were found:
+----------------+--------------------+
| Unknown Symbol | Guessed Dependency |
+----------------+--------------------+
| mixed          |                    |
+----------------+--------------------+
Command exited with non-zero status 1
```

from this method signature: 

```
    private function parseBooleanParameter(string $column, mixed $value): bool
```

**Comment by Ocramius** [comment]
Maybe same as https://github.com/maglnet/ComposerRequireChecker/issues/349 ?

**Comment by willemstuursma** [comment]
Thanks, that is really fast. We indeed have a custom `symbol-whitelist`. I'll check if adding it fixes it.

**Comment by Ocramius** [comment]
Closing here: seems like a duplicate then :+1:

**Comment by willemstuursma** [comment]
I'm not sure if it is by design but it seems a bit un-intuitive that the language keywords have to be added to a list for this tool to work. Maybe `mixed`, `null` etc could be hardcoded.

**Comment by Ocramius** [comment]
Possibly: would suggest sending a patch for improving that, though.

**Comment by willemstuursma** [comment]
@Ocramius something like this? https://github.com/maglnet/ComposerRequireChecker/pull/355
