### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by Adirelle** [maglnet/ComposerRequireChecker#36]
Some packages provides adapters/bridges for well-known other tools/framework (e.g. adapters for Doctrine/Propel/... ). However, only one of these corresponding dependencies should be installed, and it is selected by the end developer in the root project, so it must not appear in the "require" section of composer.json, but is generally in the "require-dev" section for testing purpose.

Could it be possible to show only a warning for symbols that are provided through require-dev ?

**Comment by Ocramius** [comment]
Only if these dependencies are in the `dev-` section of the package.

Optional dependencies are not really a thing: they should be split out to
third party packages. We spent a huge amount of time doing that in D2/ZF
and are still not done with it, but I wouldn't want to reduce the errors to
just warning: having an unfulfilled dependency should be a hard stop.

**Comment by Adirelle** [comment]
>  Optional dependencies are not really a thing: they should be split out to third party packages.

Good point.
