### ISSUE TITLE
Default config path

### ISSUE THREAD

**Issue by xepozz** [maglnet/ComposerRequireChecker#361]
What do you think about adding default config file name?
It's not convenient to write always path to the file. 
It's just a line [here](https://github.com/maglnet/ComposerRequireChecker/blob/4.3.x/src/ComposerRequireChecker/Cli/CheckCommand.php#L60-L65) and above to check for path existing.
I'd like to have any default path, as the `phpunit` has. Suggest to set `composer-require-checker.json` as default.

**Comment by Ocramius** [comment]
Send a patch (with tests + docs) - imo worth doing :) 

`composer-require-checker.json` is a valid name.

Tests should cover:

 * no config file
 * config file existing, detected
 * config file existing, argument with different location provided
