### ISSUE TITLE
Expose a composer plugin

### ISSUE THREAD

**Issue by VincentLanglet** [maglnet/ComposerRequireChecker#363]
Maybe I missing some knowledge or/and I missed a similar issue but,

What about exposing a composer plugin for this library ?

As an example
- composer-normalize includes the plugin inside the library
https://github.com/ergebnis/composer-normalize/blob/main/src/NormalizePlugin.php
it allows running `composer normalize`

- `composer-unused` exposes another library with the plugin
https://github.com/composer-unused/composer-unused-plugin/blob/main/src/UnusedPlugin.php
it allows running `composer unused`

Same could be provide by this library, with something like `composer require-check`, no ?

**Comment by Ocramius** [comment]
This project exposes a binary, so having it as a plugin doesn't bring additional value.

 * it can be installed globally, but that's a mistake for you to make. Global state and whatnot :P
 * it should be maintained locally to your project, via either `.phar` download or `composer.lock` (dedicated or mixed with your main project's dependencies - your pick)

Overall not something worth pursuing, especially as composer plugin complexity/maintenance is almost always non-trivial.
