### ISSUE TITLE
Reporting missing `ext-random` an PHP 8.2

### ISSUE THREAD

**Issue by rieschl** [maglnet/ComposerRequireChecker#364]
I just tried running the CI on PHP 8.2 (RC7) on one of our repositories and the require checker reported following:
```
> vendor/bin/composer-require-checker --config-file=composer-require-checker.json
ComposerRequireChecker 4.3.0@194cf647357b7077c63eee84653df2b0655b8845
The following 1 unknown symbols were found:
+----------------+--------------------+
| Unknown Symbol | Guessed Dependency |
+----------------+--------------------+
| random_int     | ext-random         |
+----------------+--------------------+
```

While technically this is correct, because 8.2 introduced a new `ext-random` extension for all the random stuff, the extension is bundled with php and cannot be disabled. So it seems to be useless to add `ext-random` to the `require` section of the `composer.json` file.

Should `ext-random` be whitelisted automatically?

Thanks for your help!

**Comment by Ocramius** [comment]
Feel free to send a patch alike #351 👍

**Comment by rieschl** [comment]
@Ocramius is targeting `3.3.2` correct? This branch is over a year old. Did you mean `4.3.1` 🙂

**Comment by Ocramius** [comment]
Good catch 😁

**Comment by rieschl** [comment]
meh, maybe we should wait until PHP 8.2.1. `ReflectionExtension` does not recognize `random` in PHP 8.2.0 (`Extension "random" does not exist`) 🙄

**Comment by Ocramius** [comment]
Handled in #367
