### ISSUE TITLE
[Question] Monorepo setup

### ISSUE THREAD

**Issue by TheCelavi** [maglnet/ComposerRequireChecker#366]
Does anyone have any experience using this tool within monorepo setup? Care to share?

Thanks!

**Comment by Ocramius** [comment]
You probably want to run it against individual `composer.json` files present in your repo (one per component) rather than once for all.

Closing here meanwhile, since it's not really an open issue :)

**Comment by TheCelavi** [comment]
Problem with that approach is that monorepo consist of several packages, A, B, C, D.... etc.

Let say that C depends on A and B. So  composer-C.json has A -> 1.0, B -> 1.0

We are preparing a new release of monorepo (everything, A, B, C... etc), in version of 2.0.  In that matter, we can not use deps stated in composer-C.json, they are not published yet. We want to use A and B within C from local monorepo, that is, we would like to "tell" to require checker that instead of using library from vendor directory, to use from local directory.

I could change composer-C.json, but I can not commit such composer file. 

In general - it seams impossible to make composer-require-checker part of CI within monorepo environment when there is interdependency. Or am I wrong?

**Comment by TheCelavi** [comment]
@Ocramius have you used composer-require-checker within monorepo with package interdependencies as part of CI? Care to share setup pointers? Thanks!

**Comment by SvenRtbg** [comment]
I apologize for the remark ahead of time, but maybe out of curiosity for myself: 

If you have a monorepo, why do you have to deal with versions anyways? Shouldn't it be "include main branch" all the time for anything also included in the repo? And why would code that is maintained in the same repo be sub-partitioned into separate packages and then re-assembled to a bigger software package?

Maybe I am ignorant to the benefits of monorepos, but I would assume that most likely things that are "correct by definition", like the packages included in the monorepo, should be excluded from any composer-require checks.

**Comment by Ocramius** [comment]
> We are preparing a new release of monorepo (everything, A, B, C... etc), in version of 2.0. In that matter, we can not use deps stated in composer-C.json, they are not published yet. We want to use A and B within C from local monorepo, that is, we would like to "tell" to require checker that instead of using library from vendor directory, to use from local directory.

In a monorepo scenario, I'd expect the various `composer.json` of each component referencing `self.version` of other dependencies in the repo itself, since they all move together:

```json
{
    "name": "my-monorepo/a",
    "require": {
        "my-monorepo/b": "self.version"
    },
    "repositories": [
        {
            "type": "path",
            "url": "../component-b",
            "options": {
                "symlink": true
            }
        }
    ]
}
```

If you need more flexible dependency ranges, I endorse getting rid of local references, and testing against actual published dependencies:

```json
{
    "name": "my-monorepo/a",
    "require": {
        "my-monorepo/b": "^1 || ^2  || ^3.1"
    }
}
```

In this scenario, un-published dependencies are not usable/tested, because not visible on the main packagist.org, but you can make them usable if you keep your own Satis or private packagist repository, perhaps as `-dev` versions.

**Comment by TheCelavi** [comment]
Consider, per example, symfony monorepo and one of their library (as an example only). Lets say this one: https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bridge/Doctrine/composer.json

If you checkout requirements, it depends on:

```
    "require": {
        "php": ">=8.1",
        "doctrine/event-manager": "^1.2|^2",
        "doctrine/persistence": "^2|^3",
        "symfony/deprecation-contracts": "^2.1|^3",
        "symfony/polyfill-ctype": "~1.8",
        "symfony/polyfill-mbstring": "~1.0",
        "symfony/service-contracts": "^1.1|^2|^3"
    },
```

There is no "self.version", there is no:

```
    "repositories": [
        {
            "type": "path",
            "url": "../component-b",
            "options": {
                "symlink": true
            }
        }
    ]
```

We have same setup of our monorepo as symfony, libraries A, B, C, D, each with their own composer.json, and one "main" composer.json for monorepo with all deps from all libraries. Unit tests use main composer.json and file from local directories of packages are loaded and tested (same as Symfony does).

Now, we assume that Symfony does not use "composer-require-checker", but we would like to do so. In best case scenario, we would like to:

`cd packages/package-a`
`composer run composer-require-checker`

as part of CI process, to verify that composer.json of package-a contains properly stated packages. Only thing that we do not want to is to modify composer.json of package-a in terms of describing where to find, per example, package-b, package-c of monorepo. Instead, we would like to be able to say to `composer-require-checker` - this is our package-a, this is our composer.json for package-a. Do check, but for autoloading, use main composer.json.

Does this makes sense? I have clear picture in my mind what I need to do, sorry if I am not being able to explain the issue fully and clearly. 

Thank you for your time, much appreciated.

**Comment by Ocramius** [comment]
I would start by doing something like this (pseudo-code):

```php
foreach ($packages as $package) {
    chdir($package);
    exec("composer install");
    exec("/path/to/require-checker");
}
```

Assuming your individual `composer.json` dependencies lead to a valid `vendor/` inside each `$package`, you should at least get some decent preliminary results with your current dependency range: this won't be perfect, but it should work OK for finding completely missing dependencies, at first.

For dependencies that change their classes in various versions, you may need to provide various `composer update --prefer-lowest` and `composer update` or `composer install` + `composer.lock` strategies.

**Comment by TheCelavi** [comment]
Yeah, thanks, that was what I was thinking to do, run against each package, within package. Problem is interdependencies of packages within monorepo -> how to tell composer-require-checker not to use vendor/package-b but to use ..packages/package-b -> that is my issue which I am trying to figure out...

**Comment by Ocramius** [comment]
That's where you use the `packages` declaration: it only applies to the root package, so even if you have it, downstream consumers won't notice :)

**Comment by TheCelavi** [comment]
Not sure that I am following. Let me give you an example:

I have package-a, version 1.0, with its own composer.json, and package-b, version 1.0. Package-a uses package-b.

In meantime, I have developed package-c, and package-a will stop using package-b, instead, it will use package-c.

From:

```
    "require": {
        "my/package-a": "^1.0"
    },
```

To:

```
    "require": {
        "my/package-b": "^2.0"
    },
```

Notice that I have to bump monorepo and all packages to 2.0 because of semver. So, I didn't deployed, yet, I will do that after I have run against `composer-require-checker` with success.

If cd into it and run it, it will, of course, fail. 

If I have forgot to change composer.json requirements from  "my/package-a": "^1.0" to  "my/package-b": "^2.0", it would not detect it, that is, it will, but I will not be able to specify from where  "my/package-b": "^2.0" comes from.

**Comment by Ocramius** [comment]
If it's an unreleased version, then `branch-alias` will allow you to declare `my/package-b` as `2.x-dev`

**Comment by Ocramius** [comment]
Again, I suggest that you first start with the minimal example, and then continue the exploration.

Get it working with just the current setup first.

**Comment by TheCelavi** [comment]
If someone stumbles upon this issue when using this tool and "composer-unused" too, `cwd` into each project, doing composer install and running checks is not that big of deal.

All composer deps are already cached, so there is no big of the perf. penalty for "re-download".

Just a small snippet of code in image below, beside that, you only need to instruct each individual project to use dependencies from local filesystem (second image). 

<img width="913" height="801" alt="Image" src="https://github.com/user-attachments/assets/f476dda3-099d-416d-9256-b2ec1824f327" />

<img width="559" height="109" alt="Image" src="https://github.com/user-attachments/assets/f8c4d712-d1db-4505-8c2d-0cc656c8f86e" />
