### ISSUE TITLE
Which dependency for Composer\Script\Event ?

### ISSUE THREAD

**Issue by Adirelle** [maglnet/ComposerRequireChecker#37]
I have a package that provides a script handler for Composer. It depends on Composer\Script\Event, which will be provided by Composer when it will be executed. As I do not want that every user of this package pulls the entire Composer sources, composer/composer is not listed in the dependencies. Yet  ComposerRequireChecker complains about it.

Is there any solution to this ?

**Comment by Ocramius** [comment]
@Adirelle this tool does not distinguish whether the file will be used at runtime or at install time. A simple solution is to move the script to `autoload-dev`, if that's a dev-only script.
Another solution is to have it split out to a separate package.

**Comment by Adirelle** [comment]
Let it be clear that I am talking of this with the "MyVendor\\MyClass::postPackageInstall" form: https://getcomposer.org/doc/articles/scripts.md#defining-scripts 

Putting it in a separate package makes no sense here: the script handler is here to work with the package. It is not optional. And this would only move the issue a step further: that separate package would have to require composer/composer, which would pull the whole sources in the same way.

Said otherwise: is the fact that the Composer "binary" is required to run script not enough to consider that composer/composer is (auto-)provided ?

Said in another way: this tool cannot be used to validate any package that provides Composer script handlers.

**Comment by Ocramius** [comment]
Yes, it cannot be used that way unless you explicitly require `composer/composer` too

**Comment by maglnet** [comment]
Another possibility would be to copy the config file and add the symbol `Composer\Script\Event` to the whitelist.  
https://github.com/maglnet/ComposerRequireChecker/blob/master/data/config.dist.json
