### ISSUE TITLE
Switch default branch to `4.6.x`

### ISSUE THREAD

**Issue by Ocramius** [maglnet/ComposerRequireChecker#383]
I canceled the release build thinking it was releasing the wrong tag, so it didn't finish switching release branch: https://github.com/maglnet/ComposerRequireChecker/actions/runs/3739526700

@maglnet could you make `4.6.x` the default branch, for now? :D

**Comment by maglnet** [comment]
@Ocramius I tried to change the default branch but it simply says `Could not change default branch` without any additional details.
I'll check again later, when I'm back at the desk.

**Comment by Ocramius** [comment]
No worries, not urgent :)

**Comment by maglnet** [comment]
@Ocramius I was able to change the default branch to `4.6.x`  now, closing here.
