### ISSUE TITLE
Distribution using phive & composer

### ISSUE THREAD

**Issue by jaapio** [maglnet/ComposerRequireChecker#397]
Hi,

I would like to do a suggestion about shipping this nice application. Right now we have phive, and manually installed phars. The phive team also created something that hooks nicely into composer using a composer plugin. 
I think this is a great alternative for people using composer to manage their dev dependencies. 

As an example of how it works, you can check this project I created for phpDocumentor: https://github.com/phpDocumentor/shim

If you install this package it will download the phar using phive, without you having to think about it. 

Let me know what you think, I would be happy to help you create a setup that fully automates things.

**Comment by Ocramius** [comment]
We already release PHARs

**Comment by Ocramius** [comment]
Oh, sorry, I misunderstood you here.

You want a shim package to install.

IMO a better approach is to create a `tools/<tool-name>/composer.json` and manage the dependency there, since it operates in complete memory address isolation anyway.

**Comment by jaapio** [comment]
I get where you are coming from, but does that really help new people in your projects to understand how to run the tools? I think we both agree on the part that running composer in the root of the project is easier, and as you are already shipping phars I think this adds value?

**Comment by Ocramius** [comment]
It still leads to maintenance and complexity overhead: from my end, I'm already against providing PHARs, heh

**Comment by jaapio** [comment]
Thanks for your answers, I will figure out a different way :-)
