### ISSUE TITLE
Feature request; take into account require-dev and suggest

### ISSUE THREAD

**Issue by tvdijen** [maglnet/ComposerRequireChecker#398]
Not all dependencies are _that_ hard..
Sometimes dependencies are only relevant in tests (dev) or are optional (suggest).

**Comment by Ocramius** [comment]
This package is precisely here to say **no** to that philosophy.

**Comment by tvdijen** [comment]
At least provide a way to exclude something

**Comment by Ocramius** [comment]
That's already supported: https://github.com/maglnet/ComposerRequireChecker/blob/e128a3234aff1c0d63bfa2aecbe3a2bf71ec2796/data/config.dist.json#L2

**Comment by tvdijen** [comment]
Ah, well hidden feature! Thanks!

**Comment by tvdijen** [comment]
One downside of this approach is that I have to specify many symbols while my goal is to whitelist a specific dependency. Would you consider a `dependency-whitelist` config-setting?

**Comment by Ocramius** [comment]
No, as I mentioned before, this tool is designed specifically to identify what people used to call "soft dependencies" or "optional dependencies", and prevent that from being abused.

The exclusion map is designed to exclude cases of mis-detection, limitations of the tool, or weirdness that can't really be explained, but it is not supposed to aid in designing for optional dependencies: optional dependencies should generally be eradicated.
