### ISSUE TITLE
PHP Attributes support

### ISSUE THREAD

**Issue by kkreft** [maglnet/ComposerRequireChecker#404]
Hi all,
thanks for this this cool tool, looks like something I've been missing for a long time :) 

I noticed that `ComposerRequireChecker` does not treat PHP attributes as symbols so it does not count them during the analysis. I've recently used https://github.com/JetBrains/phpstorm-attributes in my code and already ended up with failed deployment as I didn't noticed it was installed as a project's dev dependency, therefore it was missing on production where dev dependencies are ignored.

1. Is it there any chance such improvement could be implemented? Is someone already working on it?
2. Is it possible to provide own definition of Symbols which could be injected into the checker to extend its behaviour?

**Comment by Ocramius** [comment]
I would say that the implementation of attributes is feasible: send a patch, but it would be for a new major version.

No new configuration needed: existing configuration should cover attributes (since they are classes) just fine.

**Comment by Levivb** [comment]
Seems implemented in https://github.com/maglnet/ComposerRequireChecker/pull/527

not as a major though 😅 


We're getting this after a `composer update`:
```
+-------------------------------+--------------------+
| Unknown Symbol                | Guessed Dependency |
+-------------------------------+--------------------+
| JetBrains\PhpStorm\ArrayShape |                    |
+-------------------------------+--------------------+
```

Will probably use the `symbol-whitelist` in the config for this since it's not really meant as production dependency

**Comment by Ocramius** [comment]
Yep, indeed decided to roll in a minor: my bad for not making this clear, but indeed expanding tool scope is valid, and should require looking at.

It won't break any downstream API, so we're good on that.

Closing here meanwhile :+1:
