### ISSUE TITLE
QuadernoBase and all Quaderno classes are unknown

### ISSUE THREAD

**Issue by VincentLanglet** [maglnet/ComposerRequireChecker#476]
Hi, thanks for this great tool.

I have the following library https://github.com/quaderno/quaderno-php in my composer.json (and lock)
```
"quaderno/quaderno": "2.1.*",
```

But when running
```
vendor/bin/composer-require-checker
```
all quaderno classes are considered as unknown.

The autoload is made by a file https://github.com/quaderno/quaderno-php/blob/master/composer.json#L20-L22
When I installed the quaderno lib I could use it without extra config/loading.
So I assume this tool could be able to do the same (?)

**Comment by Ocramius** [comment]
That's because that library declares its own autoloader, and this library will **not** (by design) use it.

https://github.com/quaderno/quaderno-php/blob/58960243972dd43a25907cf195d8ecd152905d2b/composer.json#L21

Upstream Library should declare a PSR autoloader or classmap.
