### ISSUE TITLE
Detect dependencies that aren't used

### ISSUE THREAD

**Issue by Bilge** [maglnet/ComposerRequireChecker#502]
The _about_ section for this program claims, it is _a CLI tool to check whether a specific composer package uses imported symbols that aren't part of its direct composer dependencies_, but can it do **the opposite**? That is, if I reference a dependency I don't actually use, will it tell me I can safely get rid of it? e.g. I require `ext-json` but don't actually make any JSON function calls that require that extension?

**Comment by DanielBadura** [comment]
No this tool can not really help about that. But there is this here which tries to achieve this problem scope: https://github.com/composer-unused/composer-unused

**Comment by fredden** [comment]
It's possible to do this in a round-about way with this tool. Remove all entries from `require` and `require-dev` in `composer.json`, then run this tool and fix the reported issues until it doesn't complain any more. The result will be the leanest set of dependencies.

**Comment by Ocramius** [comment]
https://github.com/composer-unused/composer-unused indeed the way.
