### ISSUE TITLE
xdebug max nesting level issue

### ISSUE THREAD

**Issue by Soullivaneuh** [maglnet/ComposerRequireChecker#53]
With a quite big PHP project:

```
sullivan@7a64e1e9f7f3:/code$ php composer-require-checker.phar 
ComposerRequireChecker 0.2.0

Fatal error: Uncaught Error: Maximum function nesting level of '256' reached, aborting! in phar:///code/composer-require-checker.phar/src/ComposerRequireChecker/NodeVisitor/DefinedSymbolCollector.php on line 49

Error: Maximum function nesting level of '256' reached, aborting! in phar:///code/composer-require-checker.phar/src/ComposerRequireChecker/NodeVisitor/DefinedSymbolCollector.php on line 49
```

This max nesting level should be increased via `ini_get` or xdebug should be disabled at runtime if you don't need it.

**Comment by Ocramius** [comment]
> This max nesting level should be increased via `ini_get` or xdebug should be disabled at runtime if you don't need it.

@Soullivaneuh that's not something this tool should be responsible for: you will get the same kind of issue on anything designed to perform recursive analysis.

**Comment by Soullivaneuh** [comment]
Well, is xdebug needed here? Composer found a way to disable it while running the command AFAIK.

**Comment by Ocramius** [comment]
Yes, but any static analysis tool would have to do the same as well. Just disable XDebug as needed here: asking the tooling to control your environment is very backwards.

**Comment by Soullivaneuh** [comment]
the xdebug disabling logic is available as a package: https://packagist.org/packages/composer/xdebug-handler

It looks quite simple to implement: https://github.com/vimeo/psalm/pull/350/files

It's maybe not our role to disable it, but IMHO it worth it.

**Comment by Ocramius** [comment]
Again: by that logic, any CLI script out there in the wild should do this.

No, that's wrong and it should simply not be done: run without XDebug when you need to run without XDebug.

This kind of wrapper is something you can implement in your own logic when instantiating the kernel of a performance-critical application.
