### ISSUE TITLE
Do I need this package when I use static analyzer? 

### ISSUE THREAD

**Issue by ghost** [maglnet/ComposerRequireChecker#543]
This package checks for symbols and functions from soft dependencies But if a soft dependency is removed then static analyzer like PHPStan (even at lowest level 0 https://phpstan.org/user-guide/rule-levels) will catch this. Then this package is superfluous, right?

**Comment by Ocramius** [comment]
> But if a soft dependency is removed then static analyzer like PHPStan (even at lowest level 0 [phpstan.org/user-guide/rule-levels](https://phpstan.org/user-guide/rule-levels)) will catch this.

This depends on whether you are running your static analyzer on `composer install --no-dev` or not :-)

If you run PHPStan / Psalm with `--no-dev` sources, you should be fine without this package :+1: 

BTW, I still suggest you also run static analysis over your test suite too (separate pipeline with everything included, perhaps).
