### ISSUE TITLE
Missing composer.lock in release

### ISSUE THREAD

**Issue by patka-123** [maglnet/ComposerRequireChecker#549]
Hello,

From release 4.10.0 onward the composer.lock file has been removed from the release tarball. Is this unintentional or was this done on purpose? I'm asking because I'm maintaining the Nix package, and we build from source and require the lock-file.

Is it possible to get it back?

**Comment by SvenRtbg** [comment]
I think this was the PR back then: https://github.com/maglnet/ComposerRequireChecker/pull/530

**Comment by patka-123** [comment]
Thanks for the link!

Excluding the composer.lock in there does seem like a mistake though. ComposerRequireChecker is meant as a standalone cli app as is [explained in the readme](https://github.com/maglnet/ComposerRequireChecker?tab=readme-ov-file#installation--usage), and as such it is important to keep the lock file.

In some cases where the project is a library one might choose to not include a lock file, but even that is no longer a recommendation according to the Composer documentation.

I'll create a PR to put it back, if that's ok

**Comment by fredden** [comment]
> we build from source and require the lock-file.

The lock file /is/ in the source. How are you obtaining a copy of the source code at a certain version?

**Comment by Ocramius** [comment]
@patka-123 if you build from source, please don't use the artifact.
