### ISSUE TITLE
Missing `posix_kill`

### ISSUE THREAD

**Issue by mvhirsch** [maglnet/ComposerRequireChecker#553]
I recently added this tool in a project I was assigned on to upgrade it. This project uses `posix_kill` (looks like I need to migrate to `symfony/process` too :sweat_smile: ):

```php
class Worker
{
    // ...

    /**
     * Kill a forked child job immediately. The job it is processing will not
     * be completed.
     */
    public function killChild(): void
    {
        // truncated

        if (exec('ps '.$this->child, $output, $returnCode) && 1 != $returnCode) {
            $this->logger->notice('Killing child at '.$this->child);
            posix_kill($this->child, SIGKILL);
            $this->child = null;
        } else {
            $this->logger->notice('Child '.$this->child.' not found, restarting.');
            $this->shutdown();
        }
    }
}
```

As far as I can tell, this should be [provided by default](https://www.php.net/manual/en/posix.installation.php), unless explicitly disabled at compile time. 

https://www.php.net/manual/en/function.posix-kill.php

I :heart: this tool. It helps me keep my dependencies on track. Thank you!

**Comment by Ocramius** [comment]
This has to be reported to upstream `symfony/process`, not here: we're only relying on that as a dependency to run CLI processes :-) 

Alternatively, we'd need a different tool to spawn/track/kill processes.

**Comment by fredden** [comment]
@mvhirsch given `posix` extension can be disabled, one cannot rely on it being present / available, so should list it as a requirement in `composer.json`. Also, the extension [isn't available on Windows](https://www.php.net/manual/en/intro.posix.php), so listing it as a requirement will mean that Composer will complain rather than the application crashing at runtime due to an undefined function call.

**Comment by Ocramius** [comment]
@fredden that's also fine, but it should be in the library using these extensions.

@mvhirsch I may have misunderstood the issue though: is it that you are analyzing code that is reported as faulty, but then runs by default? I'd say that an explicit dependency should indeed be declared, or perhaps the core function should be listed under a different extension in php-src.

**Comment by mvhirsch** [comment]
I'm not able to require `ext-posix` (I already tried that first):

```
$ composer require ext-posix
Could not find package ext-posix.
```

@Ocramius seems like. I made a joke about migrating my code that actually uses `posix_kill` (directly) to migrate my code to symfony/process (in the future). Sorry for that.

 As @fredden pointed out, this can be disabled. But I already have written this above. It can only be disabled at compile-time. By default PHP includes posix (as far as I understood the documentation). However, I weren't aware of the fact it's not available on Windows. 

That being said: I'm unable to require it using composer and this library reports it. I'm fine with the fact it doesn't be a bug on this side - but how am I able to solve it? Putting it into symbol-whitelist? Any clues?

**Comment by Ocramius** [comment]
> `composer require ext-posix`

`composer require` does not (AFAIK) allow extensions anyway: would need to add it to the `"require"` section manually, then run `composer update nothing` to refresh your `composer.lock`

**Comment by mvhirsch** [comment]
I'll try updating composer.json manually :+1:

**Comment by fredden** [comment]
> `composer require ext-posix`

This works for me when the extension is installed & enabled, but otherwise not. https://stackoverflow.com/a/78372311/247863
