### ISSUE TITLE
Parsing the file [...StateProvider.tpl.php] resulted in an error: Syntax error, unexpected T_NAMESPACE on line 5

### ISSUE THREAD

**Issue by kochen** [maglnet/ComposerRequireChecker#555]
Cross referencing from:  https://github.com/api-platform/core/issues/6826

```json
{
    "name": "api-platform/issue-2805",
    "type": "project",
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "require-dev": {
        "maglnet/composer-require-checker": "^4.14"
    },
    "require": {
        "api-platform/core": "4.0.10"
    }
}
```

```
$ vendor/bin/composer-require-checker
ComposerRequireChecker 4.14.0@b6d5acd89d0de1727c1188157fa99552c39d1dfb
In LocateASTFromFiles.php line 41:
                                                                               
  Parsing the file [.../vendor/api-platform/core/src/Laravel/Console/Maker/Resources/skeleton/StateProvider.tpl.php] resulted in   
  an error: Syntax error, unexpected T_NAMESPACE on line 5                     
                                                                               
In ParserAbstract.php line 321:
                                                  
  Syntax error, unexpected T_NAMESPACE on line 5  
                                                  
check [--config-file CONFIG-FILE] [--ignore-parse-errors] [--output OUTPUT] [--] [<composer-json>]
```

Is there a way to resolve this from the checker side?

M.

**Comment by kochen** [comment]
The file in question is a simple template file:
```php
<?php

declare(strict_types=1);

namespace {{ namespace }};

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProviderInterface;

final class {{ class_name }} implements ProviderInterface
{
    public function provide(Operation $operation, array $uriVariables = [], array $context = []): object|array|null
    {
        // Retrieve the state from somewhere
    }
}
```

**Comment by Ocramius** [comment]
That's indeed not valid PHP, and it shouldn't be part of autoloaded sources, TBH.

It will also trip tools like `php -l` (in upstream PHP), so I think this sort of problem should be handled downstream, in the library that declares it as `.php` (make it `.php.tpl` instead of `.tpl.php`? )

**Comment by Ocramius** [comment]
Also, hi, long time no see! :wave:

**Comment by kochen** [comment]
> That's indeed not valid PHP, and it shouldn't be part of autoloaded sources, TBH.
> 
> It will also trip tools like `php -l` (in upstream PHP), so I think this sort of problem should be handled downstream, in the library that declares it as `.php` (make it `.php.tpl` instead of `.tpl.php`? )

This was already reported downstream, just added it here for completeness.
Weird enough, the companion template in the same directory doesn't result in a Syntax error - but it could be a race condition and this one just failed first.

**Comment by kochen** [comment]
> Also, hi, long time no see! 👋

indeed long! 👋
