### ISSUE TITLE
Checker doesn't see php-core-extensions section from config file

### ISSUE THREAD

**Issue by ondrejmirtes** [maglnet/ComposerRequireChecker#82]
Hi,
I'm running Composer Require Checker on a codebase, like this:

```
php temp/composer-require-checker-1.0.0.phar check --config-file /Users/ondrej/Development/telfa/composer-require-checker.json composer.json
```

The `composer-require-checker.json` looks like this:

```
{
	"symbol-whitelist": [
		"null",
		"true",
		"false",
		"static",
		"self",
		"parent",
		"array",
		"string",
		"int",
		"float",
		"bool",
		"iterable",
		"callable",
		"void",
		"object"
	],
	"php-core-extensions": [
		"Core",
		"date",
		"pcre",
		"Phar",
		"Reflection",
		"SPL",
		"standard"
	]
}
```

The problem is that it still reports PHP core extensions:

```
ComposerRequireChecker 1.0.0
The following unknown symbols were found:
+-----------------------+--------------------+
| unknown symbol        | guessed dependency |
+-----------------------+--------------------+
| Exception             | ext-Core           |
| filter_var            | ext-filter         |
| FILTER_VALIDATE_EMAIL | ext-filter         |
| SplObjectStorage      | ext-SPL            |
| var_dump              | ext-standard       |
| count                 | ext-standard       |
| DateTimeImmutable     | ext-date           |
| base64_encode         | ext-standard       |
| DATE_ISO8601          | ext-date           |
| var_export            | ext-standard       |
| date_get_last_errors  | ext-date           |
| preg_match            | ext-pcre           |
+-----------------------+--------------------+
```

It does not ignore the first part of the config file because the keywords are no longer reported.

**Comment by maglnet** [comment]
Hi,

did you eventually forgot to require `php`?
How does your `composer.json` look like?

Best regards,
Matthias

Am 22. August 2018 11:50:39 MESZ schrieb "Ondřej Mirtes" <notifications@github.com>:

**Comment by ondrejmirtes** [comment]
Yes, `php` in `require` was the missing thing 😊 I wasn't able to figure that out from the output.

**Comment by maglnet** [comment]
Ok, great.
I think of the following improvement:
If the guessed dependency is one of the extensions listed within `php-core-extensions` the guessed dependency should be `php`.
Opinions?

**Comment by freiondrej** [comment]
@maglnet I definitely agree. Today I ran into the very same issue and only because of the discussion in this issue I was able to find out why are the php-core-extensions "ignored".
