### ISSUE TITLE
Support for metapackages (type: metapackage, type:symfony-pack)

### ISSUE THREAD

**Issue by dkarlovi** [maglnet/ComposerRequireChecker#83]
[Composer has a concept of `metapackage` package type](https://getcomposer.org/doc/04-schema.md#type) which allows a package to declare multiple dependencies, but the user only requires the metapackage.

Symfony takes advantage of this with [packs](https://getcomposer.org/doc/04-schema.md#type), for example [`orm-pack`](https://github.com/symfony/orm-pack) or [`profiler-pack`](https://github.com/symfony/profiler-pack) and users are encouraged to install those instead of regular packages since Symfony 4 and introduction of Symfony Flex.

This obviously means any deps declared by the pack is marked by the tool as invalid, even though the pack's specific purpose is to be a transitive dependency.

I propose to include support for such packages and mark all their direct dependencies as if they were "unpacked".

Since not all packages marked with `type: metapackage` will follow the same strict versioning discipline as Symfony packs, it might make sense to leave it up to the end user which package types to trust like this, example

```
# no metapackages
bin/crc 

# trust both type: metapackage and type: symfony-pack
bin/crc --include-metapackage

# trust only type: symfony-pack
bin/crc --include-metapackage=symfony-pack
```

Or similar.

/cc @alcaeus @tgalopin

**Comment by dkarlovi** [comment]
See the Twitter thread starting here: https://twitter.com/dkarlovi/status/1032187403585441792

**Comment by Ocramius** [comment]
This is a clear "NO".

The idea of introducing dependency checks is to avoid any kind of instability, and having an in-between meta-package is only leading to unstable dependencies that may bump independently as per composer's SAT solving mechanism.

A similar example is `zendframework/zendframework`, which is a meta-package pointing to all its components: requiring it and using symbols from the `Zend\` namespace without requiring their originating packages explicitly is a violation that directly goes against the design principles of this tool, and will therefore lead to a failure.

**Comment by tgalopin** [comment]
I like how everyone is open to dialogue and read all the messages about packs being specific packages ;) . Anyway, I spent too much time on this, I won't fight for it :) .

**Comment by Ocramius** [comment]
@tgalopin it's not an opinion: this is the design principle of the package, and why the package was designed in first place. If people want to work around it, they should simply not add a dependency check tool to their test automation.

**Comment by dkarlovi** [comment]
Alright, fair enough. :+1: 

I guess you can always unpack on CI and then run the tool as-is which is close enough.

**Comment by SvenRtbg** [comment]
If you are interested in running the require checker, you should know what it's about. It requires you to explicitly declare all dependencies. Symfony packs are full of indirect dependencies, and all problems with them are valid.

Fabien recommends to unpack the packs if you want to have control over the installed dependencies. http://fabien.potencier.org/symfony4-unpack-the-packs.html

If you care about declaring explicit dependencies by using this checker, you have to unpack the packs. I don't think this has major drawbacks because I understand that the packs simply have the intention to speed up installing dependencies when starting a new project.
