### ISSUE TITLE
Parser error - how to debug it?

### ISSUE THREAD

**Issue by ondrejmirtes** [maglnet/ComposerRequireChecker#92]
Hi,
I'm experiencing this parse error in phpstan/playground project. Here it can be seen in this pull request: https://github.com/phpstan/playground/pull/13

```
ComposerRequireChecker 1.1.0

In ParserAbstract.php line 313:

  Syntax error, unexpected ';', expecting T_VARIABLE or '{' or '$' on line 4


check [--config-file CONFIG-FILE] [--ignore-parse-errors] [--] [<composer-json>]
```

I have no idea if it comes from the require checker itself or if I have a parse error somewhere in my dependencies.

**Comment by Ocramius** [comment]
Did you try with `-vvv`?

**Comment by ondrejmirtes** [comment]
Also it's interesting that on Travis the message is different:

```
2018-10-12 07:59:05 (2.91 MB/s) - ‘temp/composer-require-checker-1.1.0.phar’ saved [442533/442533]
ComposerRequireChecker 1.1.0
In ParserAbstract.php line 313:
                                             
  Syntax error, unexpected T_ECHO on line 3
```

**Comment by Ocramius** [comment]
Ah, so it is a parsing error on some of the analysed sources. Good question
then: I don't think it's up to this library to define whether sources are
parseable or not, but one thing that can be done here is running everything
with the debugger and putting a break point at the first exception, then
inspecting call parameters for the entire trace. Can most likely be
improved by adding tge parsed files to a PSR-3 logger throwing things at
STDERR.

**Comment by vlobovikov** [comment]
I think that I have similar problem:
Tested with ComposerRequireChecker 1.0.0 & ComposerRequireChecker 1.1.0
php composer-require-checker.phar check -vvv

In ParserAbstract.php line 313:

  [PhpParser\Error]
  Syntax error, unexpected T_IMPLEMENTS, expecting T_STRING on line 43


Exception trace:
 PhpParser\ParserAbstract->doParse() at phar:///srv/.../composer-require-checker.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:156
 PhpParser\ParserAbstract->parse() at phar:///.../composer-require-checker.phar/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php:51
 PhpParser\Parser\Multiple->tryParse() at phar:///.../composer-require-checker.phar/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php:32
 PhpParser\Parser\Multiple->parse() at phar:///..../composer-require-checker.phar/src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php:35
 ComposerRequireChecker\ASTLocator\LocateASTFromFiles->__invoke() at phar:///.../composer-require-checker.phar/src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRoots.php:27
 ComposerRequireChecker\DefinedSymbolsLocator\LocateDefinedSymbolsFromASTRoots->__invoke() at phar:///srv/.../composer-require-checker.phar/src/ComposerRequireChecker/Cli/CheckCommand.php:76
 ComposerRequireChecker\Cli\CheckCommand->execute() at phar:///.../composer-require-checker.phar/vendor/symfony/console/Command/Command.php:251
 Symfony\Component\Console\Command\Command->run() at phar:///srv/.../composer-require-checker.phar/vendor/symfony/console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at phar:///srv/.../composer-require-checker.phar/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at phar:///srv/.../composer-require-checker.phar/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at phar:///srv/.../composer-require-checker.phar/bin/composer-require-checker.php:32
 include() at ..../composer-require-checker.phar:10

I have the message with generated library from swaggehub. But, the problem have not every library from swaggehub
here is composer.json:

{
    "name": "any/name",
    "version": "1.0",
    "description": "",
    "keywords": [
        "swagger",
        "php",
        "sdk",
        "api"
    ],
    "homepage": "http://swagger.io",
    "license": "proprietary",
    "authors": [
        {
            "name": "Swagger and contributors",
            "homepage": "https://github.com/swagger-api/swagger-codegen"
        }
    ],
    "require": {
        "php": ">=5.5",
        "ext-curl": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "guzzlehttp/guzzle": "^6.2"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8",
        "squizlabs/php_codesniffer": "~2.6",
        "friendsofphp/php-cs-fixer": "~1.12"
    },
    "autoload": {
        "psr-4": { "...\\V1\\" : "src/" }
    },
    "autoload-dev": {
        "psr-4": { "...\\V1\\" : "test/" }
    }
}

**Comment by Ocramius** [comment]
Assigned back, sorry - we'll need the sources that crashed here.

**Comment by edmondscommerce** [comment]
I'm seeing this error, tracked it down to vendor/jakub-onderka/php-parallel-lint/tests/examples/example-04/dir1/dir2/index.php which contains clearly invalid code for testing purposes

The code in question is in the tests folder of php-parallel-lint

Unfortunately the autoload config for this library is ```  "autoload": {
        "classmap": [
            "./"
        ]
    },```

https://github.com/JakubOnderka/PHP-Parallel-Lint/blob/master/composer.json#L24

I've forked this and done a pull request, looks like there are other people having similar issues. For now I will use my fork and this library works fine

**Comment by Ocramius** [comment]
Closing here as per previous comment at https://github.com/maglnet/ComposerRequireChecker/issues/92#issuecomment-429248849:

 > I don't think it's up to this library to define whether sources are parseable or not

This sort of information is visible in traces, not really up to the lib to provide further information about crashes that are this deep in the trace, plus I'd also add that the operative assumption is that sources are well-formed PHP code.

**Comment by janopae** [comment]
> Can most likely be improved by adding tge parsed files to a PSR-3 logger throwing things at STDERR.

Has this been implemented? I still see no chance finding out which file caused the Parser error (as this would require debugging code that only lives inside a Docker image which I don't know how to do).

**Comment by Ocramius** [comment]
Yes, you should get a https://github.com/maglnet/ComposerRequireChecker/blob/5a801ae22c3423d0ee0213861158249d23e452ec/src/ComposerRequireChecker/Exception/FileParseFailed.php#L14

**Comment by janopae** [comment]
Thanks, I'll update my `composer-require-checker` version.
