### ISSUE TITLE
Unable to work with packages that don't export composer.json

### ISSUE THREAD

**Issue by duncan3dc** [maglnet/ComposerRequireChecker#97]
The [wikimedia/ip-set](https://github.com/wikimedia/IPSet) package is set to [not export composer.json](https://github.com/wikimedia/IPSet/blob/bad5eb89bff7b40fe626cb8b6caa89e7c9cf2da7/.gitattributes#L7).

This causes the [tool](https://github.com/maglnet/ComposerRequireChecker/blob/63efc5e7fc597e6fd8d41b26773be99888e1a989/src/ComposerRequireChecker/FileLocator/LocateComposerPackageDirectDependenciesSourceFiles.php#L25-L27) to ignore the package when it's installed by dist and then report the symbols as unknown.

I had a look through Composer and found that all the `composer.json` files are combined and stored in `vendor/composer/installed.json`. Before diving into it I thought I'd check what you thought about using this as the source of the `composer.json` data, rather than relying on a physical `composer.json` file in each vendor directory, or perhaps as fallback option if `composer.json` doesn't exist

**Comment by Ocramius** [comment]
@duncan3dc if `installed.json` is always guaranteed to exist, then this may work. We'd still need a test case, though...

**Comment by duncan3dc** [comment]
Fix proposed in #105
