### ISSUE TITLE
Return exit code to shell

### ISSUE THREAD

**Issue by gisostallenberg** [maglnet/ComposerRequireChecker#98]
By returning the exit code from the command this tool can be used in automation.

The last line of `bin/composer-require-checker.php` should be changed to:
```php
return $application->run();
```
This will result in the following:
```bash
$ ./vendor/bin/composer-require-checker; echo $? 
ComposerRequireChecker xxxx
The following unknown symbols were found:
+--------------------+--------------------+
| unknown symbol     | guessed dependency |
+--------------------+--------------------+
| The\Unknown\Symbol |                    |
+--------------------+--------------------+
1
```
and
```bash
ComposerRequireChecker xxxx
There were no unknown symbols found.
0
```

Do you want me to provide a PR?

**Comment by maglnet** [comment]
Since `\Symfony\Component\Console\Application::$autoExit` defaults to `true`, I don't really understand why this does not work for you.

References here:
https://github.com/symfony/console/blob/master/Application.php#L72
https://github.com/symfony/console/blob/master/Application.php#L178

```
$ bin/composer-require-checker; echo $?
ComposerRequireChecker 1.1.0-dev
The following unknown symbols were found:
+-----------------+--------------------+
| unknown symbol  | guessed dependency |
+-----------------+--------------------+
| unknownfunction |                    |
+-----------------+--------------------+
1
```

**Comment by duncan3dc** [comment]
I can't reproduce this either, I've submit some tests to ensure it works in #107

**Comment by gisostallenberg** [comment]
I'm not sure why this did not work at a given time. In a new project it does work as expected. Thanks for looking into this.
